language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
- pypy
install:
- pip install -r build_requirements.txt
- pip install -r requirements.txt
script:
- py.test -v --cov ntlmlib --cov-report term-missing ntlmlib/tests
after_success:
- coveralls
deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  distributions: sdist
  user: iclegg
  password:
    secure: r3rO2mEJXByATsc5Rqsd4+NUpGvacyhnJhZva6no1XQNgemUhE2NlABqeKnaipz/hafp+Z/0yH90Hw871lolAWDpUfI2vUZ+bOcwZ1J9EFiZwJnZn6Sb+XIyLMutBImWp2Zl8nOfFxW0Lv9OIPqtHCY+OBo97ZhPv7B0SPlhtG0=
  on:
    tags: true
    all_branches: true
    python: 2.7