language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- pypy
install:
- pip install -r build_requirements.txt
- pip install -r requirements.txt
script:
- py.test -v --cov ntlmlib --cov-report term-missing ntlmlib/tests/CI
after_success:
- printenv
- pushd .
- coveralls
- python setup.py sdist
- cd dist
- pip install ntlmlib-*.tar.gz
- echo "y" | pip uninstall ntlmlib
- popd
deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  distributions: sdist
  user: iclegg
  password:
    secure: r3rO2mEJXByATsc5Rqsd4+NUpGvacyhnJhZva6no1XQNgemUhE2NlABqeKnaipz/hafp+Z/0yH90Hw871lolAWDpUfI2vUZ+bOcwZ1J9EFiZwJnZn6Sb+XIyLMutBImWp2Zl8nOfFxW0Lv9OIPqtHCY+OBo97ZhPv7B0SPlhtG0=
  on:
    branch: release